### PR TITLE
v1.27.0 - addition of new icons docs

### PR DESCRIPTION
**Pull request by sonnyprince**
- addition of new icons docs

screen shot 2018-09-11 at 14 15 44
screen shot 2018-09-11 at 14 15 51

- [x] This PR has been checked with regard to our brand guidelines
- [x] This code has been checked with regard to our accessibility standards

## Browsers Tested

- [x] Chrome
- [x] Safari

### CODE REVIEW

**Comment by ashleynolan** [comment]
Apparently there's a conflict in the CHANGELOG – otherwise happy to merge.

**Comment by sonnyprince** [comment]
@ashleynolan conflict fixed :)

**Comment by ashleynolan** [comment]
@sonnyprince I think there are two v1.26.0 now? 😆 

Think this should be v1.27.0

https://github.com/justeat/global-component-library/pull/54

**Comment by sonnyprince** [comment]
@ashleynolan 🤦‍♂️ 🤦‍♂️ 🤦‍♂️

**Pull request merged**
